# Exported from Render on 2024-09-24T18:17:39Z
services:
- type: web
  name: ocr-4
  runtime: python
  repo: https://github.com/sampreeth4/ocr
  plan: free
  region: oregon
  buildCommand: ./render-build.sh && pip install -r requirements.txt
  startCommand: streamlit run hindiupdated.py
version: "1"
